### ISSUE TITLE
React Component - Card Search "Results" Card

### ISSUE THREAD

**Issue by JamesvanHoke** [MatthewRonaldJohnson/Magic-Tournament-Tracker#13]

**Comment by JamesvanHoke** [comment]
<a href="https://gyazo.com/1a4ec87846f95e3c774e3bf3b0db0dbf">example</a>
<a href="https://www.figma.com/file/wq3LBKimX53Cmh8DmxdX2T/Tournament-Tracker?node-id=13%3A69">full page</a>

**Comment by MatthewRonaldJohnson** [comment]
finished with CardSearch Page
